/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.lenovo.bp.search.portlet.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Document service. Represents a row in the &quot;journalarticle&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.lenovo.bp.search.portlet.model.impl.DocumentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.lenovo.bp.search.portlet.model.impl.DocumentImpl}.
 * </p>
 *
 * @author siyan
 * @see Document
 * @see com.lenovo.bp.search.portlet.model.impl.DocumentImpl
 * @see com.lenovo.bp.search.portlet.model.impl.DocumentModelImpl
 * @generated
 */
public interface DocumentModel extends BaseModel<Document> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a document model instance should use the {@link Document} interface instead.
	 */

	/**
	 * Returns the primary key of this document.
	 *
	 * @return the primary key of this document
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this document.
	 *
	 * @param primaryKey the primary key of this document
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id_ of this document.
	 *
	 * @return the id_ of this document
	 */
	public long getId_();

	/**
	 * Sets the id_ of this document.
	 *
	 * @param id_ the id_ of this document
	 */
	public void setId_(long id_);

	/**
	 * Returns the create date of this document.
	 *
	 * @return the create date of this document
	 */
	@AutoEscape
	public String getCreateDate();

	/**
	 * Sets the create date of this document.
	 *
	 * @param createDate the create date of this document
	 */
	public void setCreateDate(String createDate);

	/**
	 * Returns the article ID of this document.
	 *
	 * @return the article ID of this document
	 */
	public long getArticleId();

	/**
	 * Sets the article ID of this document.
	 *
	 * @param articleId the article ID of this document
	 */
	public void setArticleId(long articleId);

	/**
	 * Returns the version of this document.
	 *
	 * @return the version of this document
	 */
	public double getVersion();

	/**
	 * Sets the version of this document.
	 *
	 * @param version the version of this document
	 */
	public void setVersion(double version);

	/**
	 * Returns the title of this document.
	 *
	 * @return the title of this document
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this document.
	 *
	 * @param title the title of this document
	 */
	public void setTitle(String title);

	/**
	 * Returns the content of this document.
	 *
	 * @return the content of this document
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this document.
	 *
	 * @param content the content of this document
	 */
	public void setContent(String content);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.lenovo.bp.search.portlet.model.Document document);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.lenovo.bp.search.portlet.model.Document> toCacheModel();

	@Override
	public com.lenovo.bp.search.portlet.model.Document toEscapedModel();

	@Override
	public com.lenovo.bp.search.portlet.model.Document toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}