/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.lenovo.bp.search.portlet.model;

import java.io.Serializable;
import java.util.List;

import com.lenovo.bp.search.portlet.model.impl.LangContentImpl;
import com.lenovo.bp.search.portlet.model.impl.LangTitleImpl;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portlet.expando.model.ExpandoBridge;

/**
 * The base model interface for the ExtDocument service. Represents a row in the &quot;search_ExtDocument&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.lenovo.bp.search.portlet.model.impl.ExtDocumentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.lenovo.bp.search.portlet.model.impl.ExtDocumentImpl}.
 * </p>
 *
 * @author siyan
 * @see ExtDocument
 * @see com.lenovo.bp.search.portlet.model.impl.ExtDocumentImpl
 * @see com.lenovo.bp.search.portlet.model.impl.ExtDocumentModelImpl
 * @generated
 */
public interface ExtDocumentModel extends BaseModel<ExtDocument> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ext document model instance should use the {@link ExtDocument} interface instead.
	 */

	/**
	 * Returns the primary key of this ext document.
	 *
	 * @return the primary key of this ext document
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ext document.
	 *
	 * @param primaryKey the primary key of this ext document
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id_ of this ext document.
	 *
	 * @return the id_ of this ext document
	 */
	public long getId_();

	/**
	 * Sets the id_ of this ext document.
	 *
	 * @param id_ the id_ of this ext document
	 */
	public void setId_(long id_);

	/**
	 * Returns the create date of this ext document.
	 *
	 * @return the create date of this ext document
	 */
	@AutoEscape
	public String getCreateDate();

	/**
	 * Sets the create date of this ext document.
	 *
	 * @param createDate the create date of this ext document
	 */
	public void setCreateDate(String createDate);

	/**
	 * Returns the article ID of this ext document.
	 *
	 * @return the article ID of this ext document
	 */
	public long getArticleId();

	/**
	 * Sets the article ID of this ext document.
	 *
	 * @param articleId the article ID of this ext document
	 */
	public void setArticleId(long articleId);

	/**
	 * Returns the version of this ext document.
	 *
	 * @return the version of this ext document
	 */
	public double getVersion();

	/**
	 * Sets the version of this ext document.
	 *
	 * @param version the version of this ext document
	 */
	public void setVersion(double version);
	
	
	public void setListLangTitle(List<LangTitleImpl> listLangTitle);
	
	public List<LangTitleImpl> getListLangTitle();
	
	public void setListLangContent(List<LangContentImpl> listLangContent);
	
	public List<LangContentImpl> getListLangContent();	
	
	public void setUrl(String url);
	
	public String getUrl();		

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.lenovo.bp.search.portlet.model.ExtDocument extDocument);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.lenovo.bp.search.portlet.model.ExtDocument> toCacheModel();

	@Override
	public com.lenovo.bp.search.portlet.model.ExtDocument toEscapedModel();

	@Override
	public com.lenovo.bp.search.portlet.model.ExtDocument toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}