/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.lenovo.bp.search.portlet.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the LangContent service. Represents a row in the &quot;search_LangContent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.lenovo.bp.search.portlet.model.impl.LangContentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.lenovo.bp.search.portlet.model.impl.LangContentImpl}.
 * </p>
 *
 * @author siyan
 * @see LangContent
 * @see com.lenovo.bp.search.portlet.model.impl.LangContentImpl
 * @see com.lenovo.bp.search.portlet.model.impl.LangContentModelImpl
 * @generated
 */
public interface LangContentModel extends BaseModel<LangContent> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a lang content model instance should use the {@link LangContent} interface instead.
	 */

	/**
	 * Returns the primary key of this lang content.
	 *
	 * @return the primary key of this lang content
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this lang content.
	 *
	 * @param primaryKey the primary key of this lang content
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the locals of this lang content.
	 *
	 * @return the locals of this lang content
	 */
	@AutoEscape
	public String getLocals();

	/**
	 * Sets the locals of this lang content.
	 *
	 * @param locals the locals of this lang content
	 */
	public void setLocals(String locals);

	/**
	 * Returns the content of this lang content.
	 *
	 * @return the content of this lang content
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this lang content.
	 *
	 * @param content the content of this lang content
	 */
	public void setContent(String content);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.lenovo.bp.search.portlet.model.LangContent langContent);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.lenovo.bp.search.portlet.model.LangContent> toCacheModel();

	@Override
	public com.lenovo.bp.search.portlet.model.LangContent toEscapedModel();

	@Override
	public com.lenovo.bp.search.portlet.model.LangContent toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}