/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.lenovo.bp.search.portlet.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the LangTitle service. Represents a row in the &quot;search_LangTitle&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.lenovo.bp.search.portlet.model.impl.LangTitleModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.lenovo.bp.search.portlet.model.impl.LangTitleImpl}.
 * </p>
 *
 * @author siyan
 * @see LangTitle
 * @see com.lenovo.bp.search.portlet.model.impl.LangTitleImpl
 * @see com.lenovo.bp.search.portlet.model.impl.LangTitleModelImpl
 * @generated
 */
public interface LangTitleModel extends BaseModel<LangTitle> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a lang title model instance should use the {@link LangTitle} interface instead.
	 */

	/**
	 * Returns the primary key of this lang title.
	 *
	 * @return the primary key of this lang title
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this lang title.
	 *
	 * @param primaryKey the primary key of this lang title
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the locals of this lang title.
	 *
	 * @return the locals of this lang title
	 */
	@AutoEscape
	public String getLocals();

	/**
	 * Sets the locals of this lang title.
	 *
	 * @param locals the locals of this lang title
	 */
	public void setLocals(String locals);

	/**
	 * Returns the title of this lang title.
	 *
	 * @return the title of this lang title
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this lang title.
	 *
	 * @param title the title of this lang title
	 */
	public void setTitle(String title);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.lenovo.bp.search.portlet.model.LangTitle langTitle);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.lenovo.bp.search.portlet.model.LangTitle> toCacheModel();

	@Override
	public com.lenovo.bp.search.portlet.model.LangTitle toEscapedModel();

	@Override
	public com.lenovo.bp.search.portlet.model.LangTitle toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}