/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.lenovo.bp.search.portlet.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Search service. Represents a row in the &quot;journalarticl_operator&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.lenovo.bp.search.portlet.model.impl.SearchModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.lenovo.bp.search.portlet.model.impl.SearchImpl}.
 * </p>
 *
 * @author siyan
 * @see Search
 * @see com.lenovo.bp.search.portlet.model.impl.SearchImpl
 * @see com.lenovo.bp.search.portlet.model.impl.SearchModelImpl
 * @generated
 */
public interface SearchModel extends BaseModel<Search> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a search model instance should use the {@link Search} interface instead.
	 */

	/**
	 * Returns the primary key of this search.
	 *
	 * @return the primary key of this search
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this search.
	 *
	 * @param primaryKey the primary key of this search
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this search.
	 *
	 * @return the ID of this search
	 */
	public long getId();

	/**
	 * Sets the ID of this search.
	 *
	 * @param id the ID of this search
	 */
	public void setId(long id);

	/**
	 * Returns the journalarticl_id of this search.
	 *
	 * @return the journalarticl_id of this search
	 */
	public long getJournalarticl_id();

	/**
	 * Sets the journalarticl_id of this search.
	 *
	 * @param journalarticl_id the journalarticl_id of this search
	 */
	public void setJournalarticl_id(long journalarticl_id);

	/**
	 * Returns the operat_type of this search.
	 *
	 * @return the operat_type of this search
	 */
	public long getOperat_type();

	/**
	 * Sets the operat_type of this search.
	 *
	 * @param operat_type the operat_type of this search
	 */
	public void setOperat_type(long operat_type);

	/**
	 * Returns the operat_time of this search.
	 *
	 * @return the operat_time of this search
	 */
	public Date getOperat_time();

	/**
	 * Sets the operat_time of this search.
	 *
	 * @param operat_time the operat_time of this search
	 */
	public void setOperat_time(Date operat_time);

	/**
	 * Returns the user ID of this search.
	 *
	 * @return the user ID of this search
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this search.
	 *
	 * @param userId the user ID of this search
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this search.
	 *
	 * @return the user uuid of this search
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this search.
	 *
	 * @param userUuid the user uuid of this search
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the structure ID of this search.
	 *
	 * @return the structure ID of this search
	 */
	@AutoEscape
	public String getStructureId();

	/**
	 * Sets the structure ID of this search.
	 *
	 * @param structureId the structure ID of this search
	 */
	public void setStructureId(String structureId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.lenovo.bp.search.portlet.model.Search search);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.lenovo.bp.search.portlet.model.Search> toCacheModel();

	@Override
	public com.lenovo.bp.search.portlet.model.Search toEscapedModel();

	@Override
	public com.lenovo.bp.search.portlet.model.Search toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}